# Generated by Django 5.1.3 on 2024-12-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpril', '0005_tournament_max_player_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
